gstreamer1.0-plugins-base: disable ivorbis
Backport YP 2.3 Poky Meta change to disable ivorbis.
It is not expected to be required by default and removes
a dependency on tremor which is no longer in oe-core.

Fixes:
ERROR: Nothing PROVIDES 'tremor' (but meta-renesas/meta-rcar-gen3/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.6.3.bb DEPENDS on or otherwise requires it)

(From poky rev: 06272333acb1e14996232aea4692ab9f0abcd07f)

Signed-off-by: Stephen Lawrence <stephen.lawrence@renesas.com>